# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Build settings
theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Michael McCarthy
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Michael. I'm an urban planner working to make cities smarter, greener, safer, and more equitable, especially in the transportation field. 
baseurl: '/' # the subpath of your site, e.g. /blog
url: https://michaelmcc.com
permalink: /:categories/:title/
author:
  name: 'Michael McCarthy'
twitter_username: mmmccarthy
# github_username: mmmccarthy

paginate: 10

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
